apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: kalexand
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps-data
    port: 21
  - name: ftps-connection-1
    port: 30021
  - name: ftps-connection-2
    port: 30022
  - name: ftps-connection-3
    port: 30023

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021
        - containerPort: 30022
        - containerPort: 30023
        volumeMounts:
        - name: ftps-config
          mountPath: /etc/vsftpd
      volumes:
      - name: ftps-config
        configMap:
          name: ftps-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ftps-config
data:
  vsftpd.conf: |
    local_root=/
    anonymous_enable=NO
    local_enable=YES
    write_enable=YES
    local_umask=022
    dirmessage_enable=YES
    xferlog_enable=YES
    xferlog_std_format=YES
    chroot_local_user=YES
    allow_writeable_chroot=YES
    connect_from_port_20=YES
    pam_service_name=vsftpd
    seccomp_sandbox=NO
    ssl_enable=YES
    allow_anon_ssl=NO
    force_local_data_ssl=NO
    force_local_logins_ssl=NO
    require_ssl_reuse=YES
    ssl_ciphers=HIGH
    pasv_enable=YES
    pasv_promiscuous=YES
    pasv_address=192.168.99.100
    pasv_min_port=30021
    pasv_max_port=30023
    rsa_cert_file=/etc/ssl/certs/vsftpd.crt
    rsa_private_key_file=/etc/ssl/private/vsftpd.key
